package com.huawei.model;

public class BrandInfo {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_brand_info.id
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_brand_info.brand_name
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	private String brandName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_brand_info.company
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	private String company;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_brand_info.contact
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	private String contact;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_brand_info.email
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_brand_info.tel
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	private String tel;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_brand_info.remark
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	private String remark;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_brand_info.flag
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	private Boolean flag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_brand_info.id
	 * @return  the value of t_brand_info.id
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_brand_info.id
	 * @param id  the value for t_brand_info.id
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_brand_info.brand_name
	 * @return  the value of t_brand_info.brand_name
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public String getBrandName() {
		return brandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_brand_info.brand_name
	 * @param brandName  the value for t_brand_info.brand_name
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public void setBrandName(String brandName) {
		this.brandName = brandName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_brand_info.company
	 * @return  the value of t_brand_info.company
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public String getCompany() {
		return company;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_brand_info.company
	 * @param company  the value for t_brand_info.company
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public void setCompany(String company) {
		this.company = company;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_brand_info.contact
	 * @return  the value of t_brand_info.contact
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public String getContact() {
		return contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_brand_info.contact
	 * @param contact  the value for t_brand_info.contact
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public void setContact(String contact) {
		this.contact = contact;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_brand_info.email
	 * @return  the value of t_brand_info.email
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_brand_info.email
	 * @param email  the value for t_brand_info.email
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_brand_info.tel
	 * @return  the value of t_brand_info.tel
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public String getTel() {
		return tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_brand_info.tel
	 * @param tel  the value for t_brand_info.tel
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public void setTel(String tel) {
		this.tel = tel;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_brand_info.remark
	 * @return  the value of t_brand_info.remark
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_brand_info.remark
	 * @param remark  the value for t_brand_info.remark
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_brand_info.flag
	 * @return  the value of t_brand_info.flag
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public Boolean getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_brand_info.flag
	 * @param flag  the value for t_brand_info.flag
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public void setFlag(Boolean flag) {
		this.flag = flag;
	}
}