package com.huawei.model;

public class User {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.id
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.username
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.password
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column t_user.flag
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	private Boolean flag;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.id
	 * @return  the value of t_user.id
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.id
	 * @param id  the value for t_user.id
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.username
	 * @return  the value of t_user.username
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.username
	 * @param username  the value for t_user.username
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.password
	 * @return  the value of t_user.password
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.password
	 * @param password  the value for t_user.password
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column t_user.flag
	 * @return  the value of t_user.flag
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public Boolean getFlag() {
		return flag;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column t_user.flag
	 * @param flag  the value for t_user.flag
	 * @mbg.generated  Thu May 10 22:30:05 CST 2018
	 */
	public void setFlag(Boolean flag) {
		this.flag = flag;
	}
}