package com.huawei.mapper;

import com.huawei.model.BrandInfo;
import com.huawei.model.BrandInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BrandInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand_info
     *
     * @mbg.generated Thu May 10 22:30:05 CST 2018
     */
    long countByExample(BrandInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand_info
     *
     * @mbg.generated Thu May 10 22:30:05 CST 2018
     */
    int deleteByExample(BrandInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand_info
     *
     * @mbg.generated Thu May 10 22:30:05 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand_info
     *
     * @mbg.generated Thu May 10 22:30:05 CST 2018
     */
    int insert(BrandInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand_info
     *
     * @mbg.generated Thu May 10 22:30:05 CST 2018
     */
    int insertSelective(BrandInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand_info
     *
     * @mbg.generated Thu May 10 22:30:05 CST 2018
     */
    List<BrandInfo> selectByExample(BrandInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand_info
     *
     * @mbg.generated Thu May 10 22:30:05 CST 2018
     */
    BrandInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand_info
     *
     * @mbg.generated Thu May 10 22:30:05 CST 2018
     */
    int updateByExampleSelective(@Param("record") BrandInfo record, @Param("example") BrandInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand_info
     *
     * @mbg.generated Thu May 10 22:30:05 CST 2018
     */
    int updateByExample(@Param("record") BrandInfo record, @Param("example") BrandInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand_info
     *
     * @mbg.generated Thu May 10 22:30:05 CST 2018
     */
    int updateByPrimaryKeySelective(BrandInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_brand_info
     *
     * @mbg.generated Thu May 10 22:30:05 CST 2018
     */
    int updateByPrimaryKey(BrandInfo record);
}